"""Kaggle runner (generated by push.py — do not run directly).

Recreates the local project snapshot bundled below, builds an isolated Python
environment with the pinned requirements (so Kaggle's preinstalled packages
never mix in), executes the notebook cell by cell, and saves the executed
notebook to the output directory even when a cell fails. A telemetry thread
records system RAM and per-GPU memory/utilisation to telemetry.csv throughout.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

BUNDLE = __BUNDLE__
NOTEBOOK = __NOTEBOOK__
PYTHON_VERSION = __PYTHON_VERSION__

WORK = Path(os.environ.get("BER_RUNNER_WORK", "/tmp/ber"))
OUT = Path(os.environ.get("BER_RUNNER_OUT", "/kaggle/working"))
REPO = WORK / "repo"
VENV = WORK / "venv"
KERNEL = "ber-venv"


def start_telemetry(path: Path, every: int = 30, print_every: int = 300):
    """Background thread: system RAM and per-GPU memory / utilisation every `every` seconds into a CSV,
    with a summary line in the log every `print_every` seconds (Kaggle shows no live metrics via its CLI)."""
    import threading

    def ram():
        info = {}
        with open("/proc/meminfo") as f:
            for line in f:
                k, v = line.split(":")
                info[k] = int(v.split()[0]) / 1e6  # GB
        return info["MemTotal"] - info["MemAvailable"], info["MemAvailable"]

    def gpus():
        try:
            out = subprocess.run(["nvidia-smi", "--query-gpu=memory.used,utilization.gpu",
                                  "--format=csv,noheader,nounits"], capture_output=True, text=True, timeout=10).stdout
            return [tuple(float(x) for x in line.split(",")) for line in out.strip().splitlines()]
        except Exception:
            return []

    def loop():
        t0, last = time.time(), 0.0
        with open(path, "w") as f:
            f.write("seconds,ram_used_gb,ram_free_gb,gpu0_mem_mb,gpu0_util,gpu1_mem_mb,gpu1_util\n")
            while True:
                used, free = ram()
                g = gpus() + [(float("nan"), float("nan"))] * 2
                t = time.time() - t0
                f.write(f"{t:.0f},{used:.2f},{free:.2f},{g[0][0]},{g[0][1]},{g[1][0]},{g[1][1]}\n")
                f.flush()
                if t - last >= print_every:
                    last = t
                    print(f"[telemetry {t:6.0f}s] ram used {used:.1f} GB, free {free:.1f} GB | "
                          f"gpu0 {g[0][0]:.0f} MB {g[0][1]:.0f}% | gpu1 {g[1][0]:.0f} MB {g[1][1]:.0f}%", flush=True)
                time.sleep(every)

    threading.Thread(target=loop, daemon=True).start()


def run(cmd, **kw):
    print("$", " ".join(map(str, cmd)), flush=True)
    subprocess.run(list(map(str, cmd)), check=True, **kw)


def main():
    t0 = time.time()
    OUT.mkdir(parents=True, exist_ok=True)
    start_telemetry(OUT / "telemetry.csv")
    for rel, text in BUNDLE.items():
        path = REPO / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"restored {len(BUNDLE)} files into {REPO}", flush=True)

    run([sys.executable, "-m", "pip", "install", "-q", "uv"])
    run([sys.executable, "-m", "uv", "venv", "--python", PYTHON_VERSION, VENV])
    py = VENV / "bin" / "python"
    reqs = REPO / "code/business_entity_resolution/notebooks/requirements-dev.txt"
    run([sys.executable, "-m", "uv", "pip", "install", "--python", py, "-r", reqs])
    run([py, "-m", "ipykernel", "install", "--prefix", VENV, "--name", KERNEL])
    print(f"environment ready in {time.time() - t0:.0f}s", flush=True)

    nb_dir = REPO / "code/business_entity_resolution/notebooks"
    OUT.mkdir(parents=True, exist_ok=True)
    executor = r'''
import sys, time, nbformat
from nbclient import NotebookClient
src, dst, kernel = sys.argv[1:4]
nb = nbformat.read(src, as_version=4)
client = NotebookClient(nb, kernel_name=kernel, timeout=None, resources={"metadata": {"path": sys.argv[4]}})
code_cells = sum(c.cell_type == "code" for c in nb.cells)
done = [0]
t0 = time.time()
def progress(cell, cell_index, execute_reply):
    if cell.cell_type == "code":
        done[0] += 1
        print(f"[{time.time() - t0:7.0f}s] cell {done[0]}/{code_cells} done", flush=True)
client.on_cell_executed = progress
try:
    client.execute()
finally:
    nbformat.write(nb, dst)
    print(f"executed notebook written to {dst}", flush=True)
'''
    dst = OUT / f"{NOTEBOOK}.ipynb"
    env = {**os.environ, "PYTHONUNBUFFERED": "1"}
    env.pop("PYTHONPATH", None)
    run([py, "-c", executor, nb_dir / f"{NOTEBOOK}.ipynb", dst, KERNEL, nb_dir], env=env)
    run([VENV / "bin" / "jupyter", "nbconvert", "--to", "html", dst, "--output-dir", OUT])
    print(f"finished in {time.time() - t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
