"""Kaggle runner (generated by push.py — do not run directly).

Recreates the local project snapshot bundled below, builds an isolated Python
environment with the pinned requirements (so Kaggle's preinstalled packages
never mix in), executes the notebook cell by cell, and saves the executed
notebook to the output directory even when a cell fails.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

BUNDLE = __BUNDLE__
NOTEBOOK = __NOTEBOOK__
PYTHON_VERSION = __PYTHON_VERSION__

WORK = Path(os.environ.get("BER_RUNNER_WORK", "/tmp/ber"))
OUT = Path(os.environ.get("BER_RUNNER_OUT", "/kaggle/working"))
REPO = WORK / "repo"
VENV = WORK / "venv"
KERNEL = "ber-venv"


def run(cmd, **kw):
    print("$", " ".join(map(str, cmd)), flush=True)
    subprocess.run(list(map(str, cmd)), check=True, **kw)


def main():
    t0 = time.time()
    for rel, text in BUNDLE.items():
        path = REPO / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"restored {len(BUNDLE)} files into {REPO}", flush=True)

    run([sys.executable, "-m", "pip", "install", "-q", "uv"])
    run([sys.executable, "-m", "uv", "venv", "--python", PYTHON_VERSION, VENV])
    py = VENV / "bin" / "python"
    reqs = REPO / "code/business_entity_resolution/notebooks/requirements-dev.txt"
    run([sys.executable, "-m", "uv", "pip", "install", "--python", py, "-r", reqs])
    run([py, "-m", "ipykernel", "install", "--prefix", VENV, "--name", KERNEL])
    print(f"environment ready in {time.time() - t0:.0f}s", flush=True)

    nb_dir = REPO / "code/business_entity_resolution/notebooks"
    OUT.mkdir(parents=True, exist_ok=True)
    executor = r'''
import sys, time, nbformat
from nbclient import NotebookClient
src, dst, kernel = sys.argv[1:4]
nb = nbformat.read(src, as_version=4)
client = NotebookClient(nb, kernel_name=kernel, timeout=None, resources={"metadata": {"path": sys.argv[4]}})
code_cells = sum(c.cell_type == "code" for c in nb.cells)
done = [0]
t0 = time.time()
def progress(cell, cell_index, execute_reply):
    if cell.cell_type == "code":
        done[0] += 1
        print(f"[{time.time() - t0:7.0f}s] cell {done[0]}/{code_cells} done", flush=True)
client.on_cell_executed = progress
try:
    client.execute()
finally:
    nbformat.write(nb, dst)
    print(f"executed notebook written to {dst}", flush=True)
'''
    dst = OUT / f"{NOTEBOOK}.ipynb"
    env = {**os.environ, "PYTHONUNBUFFERED": "1"}
    env.pop("PYTHONPATH", None)
    run([py, "-c", executor, nb_dir / f"{NOTEBOOK}.ipynb", dst, KERNEL, nb_dir], env=env)
    run([VENV / "bin" / "jupyter", "nbconvert", "--to", "html", dst, "--output-dir", OUT])
    print(f"finished in {time.time() - t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
